osx_image: xcode9.3
language: objective-c
xcode_workspace: ui99.xcworkspace
xcode_scheme: ui99
xcode_sdk: iphonesimulator11.2

before_install:
- gem install cocoapods slather xcpretty
- pod repo update

script:
- set -o pipefail && xcodebuild clean test -sdk iphonesimulator -workspace ui99.xcworkspace -scheme ui99 -destination 'platform=iOS Simulator,name=iPhone 7' | xcpretty

after_success: slather